"""E5 -- a sequenced genotype call and an imputed one with equal content.

A sequenced call L is generated by an activity a_L (truly a contact with
reads); an imputed call Gamma by a_Gamma (truly a derivation from a reference
panel). Their content is m values (variant, reference allele, alternative
allele, genotype, and for two thirds of the sites a filter status), each
emitted per record with probability 1 - d.

Regimes:  R0 no provenance; R1 a generation edge to an activity typed only
prov:Activity; R2 R1 plus a typed activity (SequencingAssay vs
ImputationActivity); R3 R1 plus, independently with probability q each, an
associated agent (Person vs SoftwareAgent) and a used input (SequencingReads vs
ReferencePanel).

Measured: mutual indiscernibility under the type projection, whether the
transposition of the two gadgets is an automorphism of the emitted graph, and
the letter at which a separated pair is separated, against the law
  Pr[indiscernible] = (1-q)^4 ((1-d)^2 + d^2)^m.
Also: the ground of a concordance record comparing two calls.
"""

from __future__ import annotations

import time

import numpy as np

from common import rng_for, write_result
from gsv import calculus as C
from gsv import verdicts as V
from gsv.corpora import VERDICTS, verdict
from gsv.rdfgraphs import EX, PROV, ind
from rdflib.namespace import RDF

CONTENT = [("alt", "T"), ("filter", "PASS"), ("gt", "0/1"), ("ref", "C"), ("variant", "rs9")]


def emit_pair(rng, regime, q, d, m):
    """Return (triples, projections) for one twin pair."""
    T = set()
    proj = {"L": set(), "G": set()}
    content = CONTENT[:m] if m == 5 else [c for c in CONTENT if c[0] != "filter"]
    for x in ("L", "G"):
        for kv in content:
            if rng.random() >= d:
                T.add((x, kv[0], kv[1]))
                proj[x].add(kv)
    if regime == "R0":
        return T, proj
    cls = {"L": ("SequencingAssay", "Person", "SequencingReads"),
           "G": ("ImputationActivity", "SoftwareAgent", "ReferencePanel")}
    for x in ("L", "G"):
        a = "a" + x
        T |= {(x, "gen", a), (a, "type", "Activity")}
        proj[x] |= {("gen", "yes"), ("gen/type", "Activity")}
        if regime == "R2":
            T.add((a, "type", cls[x][0]))
            proj[x].add(("gen/type", cls[x][0]))
        if regime == "R3":
            if rng.random() < q:
                T |= {(a, "assoc", "ag" + x), ("ag" + x, "type", cls[x][1])}
                proj[x].add(("gen/assoc/type", cls[x][1]))
            if rng.random() < q:
                T |= {(a, "used", "in" + x), ("in" + x, "type", cls[x][2])}
                proj[x].add(("gen/used/type", cls[x][2]))
    return T, proj


def is_automorphic(T):
    sw = {"L": "G", "G": "L", "aL": "aG", "aG": "aL", "agL": "agG", "agG": "agL",
          "inL": "inG", "inG": "inL"}
    S = {(sw.get(s, s), p, sw.get(o, o)) for s, p, o in T}
    return S == T


def separation(proj):
    """Letter at which the twins are separated: '+' or '-' in the nest of L,
    '-rev' in the nest of Gamma, or None when indiscernible."""
    feats = sorted({f for x in proj for f, _ in proj[x]})
    vals = {f: sorted({v for x in proj for g, v in proj[x] if g == f}) for f in feats}
    M = np.zeros((2, len(feats)), dtype=np.int64)
    for r, x in enumerate(("L", "G")):
        for j, f in enumerate(feats):
            for k, v in enumerate(vals[f]):
                if (f, v) in proj[x]:
                    M[r, j] |= 1 << k
    if proj["L"] == proj["G"]:
        return None
    wL, cellL, _ = C.canonical_nest(M, 0)
    if not cellL[1]:
        return wL[-1] if wL else None
    wG, _, _ = C.canonical_nest(M, 1)
    return "-rev" if wG and wG[-1] == "-" else ("+rev" if wG else None)


def law(q, d, m):
    return (1 - q) ** 4 * ((1 - d) ** 2 + d ** 2) ** m


def run(rng, regime, q, d, n_pairs):
    ind_n = auto_n = disagree = 0
    letters = {"+": 0, "-": 0, "-rev": 0, "+rev": 0}
    expected = []
    for i in range(n_pairs):
        m = 4 if i % 3 == 0 else 5
        T, proj = emit_pair(rng, regime, q, d, m)
        indisc = proj["L"] == proj["G"]
        auto = is_automorphic(T)
        ind_n += indisc
        auto_n += auto
        disagree += int(indisc != auto)
        s = separation(proj)
        if s is not None:
            letters[s] += 1
        expected.append(law(q if regime == "R3" else (0.0 if regime != "R2" else 1.0), d, m))
    return {"pairs": n_pairs, "indiscernible": ind_n, "automorphic": auto_n,
            "indisc_auto_disagreements": disagree, "letters": letters,
            "predicted_indiscernible": float(np.mean(expected)) * n_pairs}


def concordance_check(rng, n=2000):
    """A concordance record kappa that compares calls x and y: generated by an
    activity that used both and was associated with software. Its ground is
    predicted to be (1, c_x or c_y, 1)."""
    bad = 0
    table = {}
    for _ in range(n):
        T = []
        recs = [ind("x"), ind("y")]
        for r in recs:
            kind = rng.integers(4)          # 0 none, 1 sequencing, 2 imputation, 3 untyped
            if kind == 0:
                continue
            a = ind(f"{r}_act")
            T.append((r, V.GEN, a))
            if kind == 1:
                T.append((a, RDF.type, EX.SequencingAssay))
            elif kind == 2:
                T.append((a, RDF.type, EX.ImputationActivity))
            else:
                T.append((a, RDF.type, PROV.Activity))
        k, ak, sw = ind("kappa"), ind("kappa_act"), ind("sw")
        T += [(k, V.GEN, ak), (ak, V.USED, recs[0]), (ak, V.USED, recs[1]),
              (ak, V.ASSOC, sw), (sw, RDF.type, PROV.SoftwareAgent)]
        g = V.graph_of(T)
        gr = V.ground_fixed_point(g, recs + [k], V.SYN)
        pred = (1, gr[recs[0]][1] | gr[recs[1]][1], 1)
        bad += int(gr[k] != pred)
        key = f"{VERDICTS[verdict(*gr[recs[0]])]}+{VERDICTS[verdict(*gr[recs[1]])]}"
        table[key] = VERDICTS[verdict(*gr[k])]
    return {"records": n, "violations": bad, "kappa_verdict_by_inputs": table}


def main():
    t0 = time.time()
    rng = rng_for(5)
    npairs = 360
    reps = 3
    base = {}
    for regime in ("R0", "R1", "R2"):
        for d in (0.0, 0.2):
            r = [run(rng, regime, 0.0, d, npairs) for _ in range(reps)]
            base[f"{regime}_d{d}"] = {k: (sum(x[k] for x in r) if not isinstance(r[0][k], dict)
                                          else {L: sum(x[k][L] for x in r) for L in r[0][k]})
                                      for k in r[0]}
    qs = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    ds = [0.0, 0.1, 0.2, 0.3]
    grid = {}
    for q in qs:
        for d in ds:
            r = [run(rng, "R3", q, d, npairs) for _ in range(reps)]
            grid[f"{q}_{d}"] = {k: (sum(x[k] for x in r) if not isinstance(r[0][k], dict)
                                    else {L: sum(x[k][L] for x in r) for L in r[0][k]})
                                for k in r[0]}
    payload = {"pairs_per_setting": npairs * reps, "baseline": base, "R3_grid": grid,
               "q": qs, "d": ds, "concordance": concordance_check(rng)}
    write_result("E5_twins", payload, t0)


if __name__ == "__main__":
    main()
