"""rdfgraphs.py -- genomic provenance graphs, identifier-blind queries, orbits.

Terms are split as in the manuscript: the vocabulary Z (predicates, classes,
variant identifiers, which are shared identities such as rsIDs) and the
individuals I (samples, calls, activities, inputs, agents, whose identity is a
matter of naming). Literals are genotype strings and read depths.
"""

from __future__ import annotations

import itertools
from collections import Counter

import networkx as nx
from networkx.algorithms.isomorphism import DiGraphMatcher
from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import RDF

EX = Namespace("http://example.org/gsv#")
PROV = Namespace("http://www.w3.org/ns/prov#")
INDNS = "http://example.org/ind/"

PREFIXES = ("PREFIX ex: <http://example.org/gsv#>\n"
            "PREFIX prov: <http://www.w3.org/ns/prov#>\n"
            "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n")

GENOTYPES = ["0/0", "0/1", "1/1"]
ACT_CLASSES = [EX.SequencingAssay, EX.ImputationActivity, PROV.Activity]
INPUT_CLASSES = [EX.Sequencer, EX.ReferencePanel, EX.BiologicalSample]
AGENT_CLASSES = [PROV.Person, PROV.SoftwareAgent]
VARIANTS = [EX[f"rs{k}"] for k in range(1, 6)]


def ind(name: str) -> URIRef:
    return URIRef(INDNS + name)


def is_individual(t) -> bool:
    return isinstance(t, URIRef) and str(t).startswith(INDNS)


# ------------------------------------------------------------ generation

def add_gadget(g: Graph, rng, tag: str, n_calls: int):
    """A sample with calls, each generated by an activity that used an input
    and was associated with an agent. Returns its individuals."""
    names = []
    s = ind(f"{tag}_sample")
    g.add((s, RDF.type, EX.Sample)); names.append(s)
    act = ind(f"{tag}_act")
    g.add((act, RDF.type, ACT_CLASSES[rng.integers(3)])); names.append(act)
    inp = ind(f"{tag}_input")
    g.add((inp, RDF.type, INPUT_CLASSES[rng.integers(3)])); names.append(inp)
    g.add((act, PROV.used, inp))
    if rng.random() < 0.6:
        ag = ind(f"{tag}_agent")
        g.add((ag, RDF.type, AGENT_CLASSES[rng.integers(2)])); names.append(ag)
        g.add((act, PROV.wasAssociatedWith, ag))
    for k in range(n_calls):
        c = ind(f"{tag}_call{k}")
        names.append(c)
        g.add((c, RDF.type, EX.GenotypeCall))
        g.add((c, EX.ofSample, s))
        g.add((c, EX.atVariant, VARIANTS[rng.integers(len(VARIANTS))]))
        g.add((c, EX.genotype, Literal(GENOTYPES[rng.integers(3)])))
        if rng.random() < 0.5:
            g.add((c, EX.depth, Literal(int(rng.integers(5, 40)))))
        g.add((c, PROV.wasGeneratedBy, act))
    return names


def random_graph(rng, n_gadgets=None):
    g = Graph()
    n_gadgets = n_gadgets or int(rng.integers(2, 4))
    for i in range(n_gadgets):
        add_gadget(g, rng, f"g{i}", int(rng.integers(1, 3)))
    # occasional cross links: an activity that used another gadget's call
    calls = [t for t in individuals(g) if "_call" in str(t)]
    acts = [t for t in individuals(g) if str(t).endswith("_act")]
    if len(calls) > 1 and rng.random() < 0.5:
        a = acts[rng.integers(len(acts))]
        c = calls[rng.integers(len(calls))]
        g.add((a, PROV.used, c))
    return g


def symmetric_graph(rng, break_symmetry: bool):
    """Two copies of one gadget (an orbit twin by construction); optionally
    broken by changing one genotype literal in the copy."""
    g = Graph()
    proto = Graph()
    names = add_gadget(proto, rng, "a", 1)
    for t in proto:
        g.add(t)
    ren = {n: ind(str(n)[len(INDNS):].replace("a_", "b_", 1)) for n in names}
    for s, p, o in proto:
        g.add((ren.get(s, s), p, ren.get(o, o)))
    if break_symmetry:
        calls = [n for n in names if "_call" in str(n)]
        c = ren[calls[0]]
        old = [o for o in g.objects(c, EX.genotype)][0]
        new = [x for x in GENOTYPES if x != str(old)][rng.integers(2)]
        g.remove((c, EX.genotype, old))
        g.add((c, EX.genotype, Literal(new)))
    add_gadget(g, rng, "z", 1)     # an unrelated gadget
    return g, names, ren


def individuals(g: Graph):
    out = set()
    for s, p, o in g:
        for t in (s, o):
            if is_individual(t):
                out.add(t)
    return sorted(out)


def vocabulary(g: Graph):
    out = set()
    for s, p, o in g:
        out.add(p)
        for t in (s, o):
            if isinstance(t, URIRef) and not is_individual(t):
                out.add(t)
    return sorted(out)


# ------------------------------------------------------------ renaming

def rename(g: Graph, pi: dict) -> Graph:
    h = Graph()
    for s, p, o in g:
        h.add((pi.get(s, s), p, pi.get(o, o)))
    return h


def random_renaming(g: Graph, rng):
    inds = individuals(g)
    pool = [ind(f"r{k:03d}") for k in range(len(inds) + 10)]
    perm = rng.permutation(len(pool))[: len(inds)]
    return {a: pool[k] for a, k in zip(inds, perm)}


# ------------------------------------------------------------ queries

FRAGMENT = {
    "bgp": "SELECT ?c ?s WHERE { ?c ex:ofSample ?s . ?c ex:atVariant ex:rs1 }",
    "optional": "SELECT ?c ?d WHERE { ?c a ex:GenotypeCall OPTIONAL { ?c ex:depth ?d } }",
    "union": "SELECT ?x WHERE { { ?x a ex:SequencingAssay } UNION { ?x a ex:ImputationActivity } }",
    "minus": 'SELECT ?c WHERE { ?c a ex:GenotypeCall MINUS { ?c ex:genotype "0/0" } }',
    "not_exists": 'SELECT ?s WHERE { ?s a ex:Sample FILTER NOT EXISTS { ?c ex:ofSample ?s . ?c ex:genotype "1/1" } }',
    "literal_filter": "SELECT ?c ?d WHERE { ?c ex:depth ?d FILTER(?d > 20) }",
    "aggregate": "SELECT ?s (COUNT(?c) AS ?n) WHERE { ?c ex:ofSample ?s } GROUP BY ?s",
    "path_sequence": "SELECT ?c ?t WHERE { ?c prov:wasGeneratedBy/prov:used/rdf:type ?t }",
    "path_closure": "SELECT ?c ?a WHERE { ?c prov:wasGeneratedBy/(prov:used/prov:wasGeneratedBy)* ?a }",
    "typed": "SELECT ?x ?y WHERE { ?x prov:used ?y FILTER(isIRI(?y)) }",
    "ask": 'ASK { ?c ex:genotype "1/1" . ?c ex:ofSample ?s }',
}

CONTROLS = {
    "lexical": "SELECT ?x ?y WHERE { ?x a ex:GenotypeCall . ?y a ex:GenotypeCall FILTER(STR(?x) < STR(?y)) }",
    "order_limit": "SELECT ?x WHERE { ?x a ex:GenotypeCall } ORDER BY ?x LIMIT 1",
    "constant": None,     # built per graph: names the first call of the original graph
}


def constant_query(g: Graph) -> str:
    calls = [t for t in individuals(g) if "_call" in str(t)]
    return f"SELECT ?v ?gt WHERE {{ <{calls[0]}> ex:atVariant ?v . <{calls[0]}> ex:genotype ?gt }}"


def answer(g: Graph, q: str):
    r = g.query(PREFIXES + q)
    if r.type == "ASK":
        return bool(r.askAnswer)
    return Counter(tuple(row) for row in r)


def map_answer(ans, pi):
    if isinstance(ans, bool):
        return ans
    return Counter(tuple(pi.get(t, t) for t in row) for row, k in ans.items()
                   for _ in range(k))


def generic(g: Graph, q: str, pi: dict) -> bool:
    return answer(rename(g, pi), q) == map_answer(answer(g, q), pi)


# ------------------------------------------------------------ orbits

def description_query(g: Graph, a) -> str:
    inds = [a] + [x for x in individuals(g) if x != a]
    var = {x: f"?x{k}" for k, x in enumerate(inds)}

    def term(t):
        if t in var:
            return var[t]
        if isinstance(t, Literal):
            return t.n3()
        return f"<{t}>"

    pats = " .\n ".join(f"{term(s)} <{p}> {term(o)}" for s, p, o in g)
    vocab = ", ".join(f"<{z}>" for z in vocabulary(g))
    conds = []
    for v in var.values():
        conds.append(f"isIRI({v})")
        conds.append(f"!({v} IN ({vocab}))")
    for u, v in itertools.combinations(var.values(), 2):
        conds.append(f"{u} != {v}")
    return f"SELECT DISTINCT ?x0 WHERE {{ {pats} FILTER({' && '.join(conds)}) }}"


def to_nx(g: Graph) -> nx.DiGraph:
    G = nx.DiGraph()
    for s, p, o in g:
        for t in (s, o):
            if t not in G:
                G.add_node(t, label="IND" if is_individual(t) else str(t))
        if G.has_edge(s, o):
            G[s][o]["label"] = tuple(sorted(G[s][o]["label"] + (str(p),)))
        else:
            G.add_edge(s, o, label=(str(p),))
    return G


def same_orbit(g: Graph, a, b) -> bool:
    G1 = to_nx(g)
    G2 = G1.copy()
    G1.nodes[a]["label"] = "MARK"
    G2.nodes[b]["label"] = "MARK"
    gm = DiGraphMatcher(G1, G2,
                        node_match=lambda x, y: x["label"] == y["label"],
                        edge_match=lambda x, y: x["label"] == y["label"])
    return gm.is_isomorphic()


def colour_refinement(g: Graph) -> dict:
    G = to_nx(g)
    col = {v: G.nodes[v]["label"] for v in G}
    for _ in range(len(G)):
        new = {}
        for v in G:
            outs = sorted((G[v][w]["label"], col[w]) for w in G.successors(v))
            ins = sorted((G[w][v]["label"], col[w]) for w in G.predecessors(v))
            new[v] = hash((col[v], tuple(outs), tuple(ins)))
        # canonical relabel to compare partitions
        if len(set(new.values())) == len(set(col.values())):
            col = new
            break
        col = new
    return col
