"""verdicts.py -- the ground of a genomic record, as a least fixed point and as
three identifier-blind SPARQL property-path queries.

Act(r) is the least set containing every activity that generated r and closed
under: a in Act(r), a used u, u generated by a'  ==>  a' in Act(r).
ground(r) = (g, c, d): g = r has a generation edge; c (d) = some activity of
Act(r) is typed as, used, or (for d) was associated with a declared contact
(derivation) class.
"""

from __future__ import annotations

from collections import defaultdict

from rdflib import Graph, Namespace, URIRef
from rdflib.namespace import RDF

from gsv.corpora import verdict
from gsv.rdfgraphs import EX, PREFIXES, PROV, ind

GEN, USED, ASSOC = PROV.wasGeneratedBy, PROV.used, PROV.wasAssociatedWith


class Witness:
    def __init__(self, A_c=(), U_c=(), A_d=(), U_d=(), G_d=()):
        self.A_c, self.U_c = set(A_c), set(U_c)
        self.A_d, self.U_d, self.G_d = set(A_d), set(U_d), set(G_d)


def types(g: Graph, x):
    return set(g.objects(x, RDF.type))


def ground_fixed_point(g: Graph, records, W: Witness) -> dict:
    gen = defaultdict(set)
    for s, _, o in g.triples((None, GEN, None)):
        gen[s].add(o)
    used = defaultdict(set)
    for s, _, o in g.triples((None, USED, None)):
        used[s].add(o)
    assoc = defaultdict(set)
    for s, _, o in g.triples((None, ASSOC, None)):
        assoc[s].add(o)
    out = {}
    for r in records:
        act = set(gen[r])
        frontier = list(act)
        while frontier:
            a = frontier.pop()
            for u in used[a]:
                for a2 in gen[u]:
                    if a2 not in act:
                        act.add(a2)
                        frontier.append(a2)
        gbit = int(bool(gen[r]))
        c = d = 0
        for a in act:
            ta = types(g, a)
            tu = set().union(*[types(g, u) for u in used[a]]) if used[a] else set()
            tg = set().union(*[types(g, x) for x in assoc[a]]) if assoc[a] else set()
            c |= int(bool(ta & W.A_c) or bool(tu & W.U_c))
            d |= int(bool(ta & W.A_d) or bool(tu & W.U_d) or bool(tg & W.G_d))
        out[r] = (gbit, c, d)
    return out


def _in(xs):
    return ", ".join(f"<{x}>" for x in sorted(xs)) or "<urn:none>"


CHAIN = "prov:wasGeneratedBy/(prov:used/prov:wasGeneratedBy)*"


def verdict_queries(W: Witness) -> dict:
    return {
        "Q_g": "SELECT DISTINCT ?r WHERE { ?r prov:wasGeneratedBy ?a }",
        "Q_c": (f"SELECT DISTINCT ?r WHERE {{ ?r {CHAIN} ?a . "
                f"{{ ?a a ?t FILTER(?t IN ({_in(W.A_c)})) }} UNION "
                f"{{ ?a prov:used ?u . ?u a ?t FILTER(?t IN ({_in(W.U_c)})) }} }}"),
        "Q_d": (f"SELECT DISTINCT ?r WHERE {{ ?r {CHAIN} ?a . "
                f"{{ ?a a ?t FILTER(?t IN ({_in(W.A_d)})) }} UNION "
                f"{{ ?a prov:used ?u . ?u a ?t FILTER(?t IN ({_in(W.U_d)})) }} UNION "
                f"{{ ?a prov:wasAssociatedWith ?x . ?x a ?t FILTER(?t IN ({_in(W.G_d)})) }} }}"),
    }


def ground_sparql(g: Graph, records, W: Witness) -> dict:
    qs = verdict_queries(W)
    sets = {k: {row[0] for row in g.query(PREFIXES + q)} for k, q in qs.items()}
    return {r: (int(r in sets["Q_g"]), int(r in sets["Q_c"]), int(r in sets["Q_d"]))
            for r in records}


# ------------------------------------------------------------ synthetic graphs

SYN = Witness(A_c=[EX.SequencingAssay, EX.Genotyping], U_c=[EX.Sequencer, EX.BiologicalSample],
              A_d=[EX.ImputationActivity, EX.VariantPrediction], U_d=[EX.ReferencePanel, EX.Model],
              G_d=[PROV.SoftwareAgent])
ACTS = [EX.SequencingAssay, EX.Genotyping, EX.ImputationActivity, EX.VariantPrediction,
        PROV.Activity, EX.Alignment]
INPUTS = [EX.Sequencer, EX.BiologicalSample, EX.ReferencePanel, EX.Model, PROV.Entity]
AGENTS = [PROV.Person, PROV.SoftwareAgent, PROV.Organization]


def random_provenance(rng, n_records=8):
    """A list of triples (to be added in any order) over records with
    generation chains through records used by later activities."""
    T = []
    recs = [ind(f"rec{k}") for k in range(n_records)]
    for r in recs:
        T.append((r, RDF.type, EX.GenomicRecord))
    k = 0
    for i, r in enumerate(recs):
        if rng.random() < 0.15:
            continue                        # no recorded generation: a symbol
        a = ind(f"act{k}"); k += 1
        T.append((r, GEN, a))
        if rng.random() < 0.8:
            T.append((a, RDF.type, ACTS[rng.integers(len(ACTS))]))
        if rng.random() < 0.5:
            u = ind(f"in{k}")
            T += [(a, USED, u), (u, RDF.type, INPUTS[rng.integers(len(INPUTS))])]
        if i > 0 and rng.random() < 0.45:
            T.append((a, USED, recs[rng.integers(i)]))       # chain to an earlier record
        if rng.random() < 0.35:
            x = ind(f"ag{k}")
            T += [(a, ASSOC, x), (x, RDF.type, AGENTS[rng.integers(len(AGENTS))])]
    return recs, T


def graph_of(triples) -> Graph:
    g = Graph()
    for t in triples:
        g.add(t)
    return g


def verdict_of(gr):
    return verdict(*gr)
