// GENERATED by synopsis/corpus/gen_ast.py from synopsis/corpus/ast.json.
// Do not edit by hand -- edit the JSON and re-run the generator.

use crate::params::Params;

#[derive(Debug, Clone, PartialEq)]
pub enum Expr {
    /// project <src> by <projector>(<args>)  -- Sec 7.3
    Project {
        line: usize,
        src: Box<Expr>,
        projector: String,
        args: Params,
    },
    /// compare <l> against <r> by <method>(<params>)
    Compare {
        line: usize,
        left: Box<Expr>,
        right: Box<Expr>,
        method: String,
        params: Params,
    },
    /// detect peaks|top in <src> { params }  -- `kind` selects the result type
    Detect {
        line: usize,
        kind: String,
        src: Box<Expr>,
        params: Params,
    },
    /// align central(a,b) response(c,d) under phi_c, phi_r { theta }  -- Thm 9.5. has_response_clause=false is the false-friend mistake the arity rule must refuse.
    Align {
        line: usize,
        central: (Box<Expr>, Box<Expr>),
        resp: Option<(Box<Expr>, Box<Expr>)>,
        corrs: Vec<String>,
        params: Params,
        has_response_clause: bool,
    },
    /// unit <src> anchors <n>  -- Def 5.4 anchors/residue split
    UnitExpr {
        line: usize,
        src: Box<Expr>,
        anchors: usize,
    },
    /// response <src> by <method>  -- method=null means ANONYMOUS, which Rule 6.7 refuses
    ResponseExpr {
        line: usize,
        src: Box<Expr>,
        method: Option<String>,
    },
    /// nearest_unit <net> to <unit>
    NearestUnit {
        line: usize,
        net: Box<Expr>,
        to: Box<Expr>,
    },
    /// corr from <src> to <dst> by <by>
    CorrExpr {
        line: usize,
        src: Box<Expr>,
        dst: Box<Expr>,
        by: String,
    },
    /// a bound name
    Var {
        line: usize,
        name: String,
    },
    /// a numeric literal
    Num {
        line: usize,
        value: f64,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum Stmt {
    /// let x = <expr>. NOTE: the reference parser has an `ann` branch for `let x : ty = e`, but ':' is not in the tokenizer's punctuation class, so that branch is unreachable -- `let x : seq` fails with `unexpected character ':'`. The field is kept (always null) so the two implementations stay structurally identical to the reference; neither compiler may start accepting the annotation without a decision, because that would extend the language.
    Let {
        line: usize,
        name: String,
        ann: Option<String>,
        expr: Box<Expr>,
    },
    /// bind v, res = <expr>  -- introduces BOTH the value and its residue; Cor 9.8 requires the residue be consumed before the frame closes
    Bind {
        line: usize,
        value: String,
        residue: String,
        expr: Box<Expr>,
    },
    /// relax <target> until quiescent { eta ; theta }  -- Thm 9.3 refuses eta <= 0
    Relax {
        line: usize,
        target: String,
        params: Params,
    },
    /// sweep x in lo..hi step s { }  or  sweep x in [..] { }  -- Thm 9.1: trip count fixed on entry. `values` non-null means the literal-list form, and lo/hi/step are then unused.
    Sweep {
        line: usize,
        var: String,
        lo: f64,
        hi: f64,
        step: f64,
        values: Option<Vec<f64>>,
        body: Vec<Stmt>,
    },
    /// for u in items(<src>) [where <guard>] { }  -- finite item set, so total
    For {
        line: usize,
        var: String,
        src: Box<Expr>,
        guard: Option<String>,
        body: Vec<Stmt>,
    },
    /// claim "text" = <expr>
    Claim {
        line: usize,
        text: String,
        expr: Box<Expr>,
    },
    /// record a, b, c  -- consumes pending residue
    Record {
        line: usize,
        names: Vec<String>,
    },
    /// drop x  -- explicitly abandons a residue; the report records that it was abandoned rather than omitting it
    Drop {
        line: usize,
        name: String,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum Decl {
    /// open name = "path"
    Open {
        line: usize,
        name: String,
        path: String,
    },
    /// method name = spec(params)  -- Rule 6.7: responses must name a declared method
    MethodDecl {
        line: usize,
        name: String,
        spec: String,
        params: Params,
    },
}

/// under <name> { }  -- Sec 7.4. Each block introduces a fresh frame index phi; types carrying different phi are DIFFERENT TYPES, which is what gives Thm 9.6.
#[derive(Debug, Clone, PartialEq)]
pub struct FrameBlock {
    pub line: usize,
    pub name: String,
    pub body: Vec<Stmt>,
}

/// the whole program. `report` is the terminal `report to "path"`; null is a ParseError, since there is no silent program (Rule 6.11).
#[derive(Debug, Clone, PartialEq)]
pub struct Program {
    pub line: usize,
    pub decls: Vec<Decl>,
    pub frames: Vec<FrameBlock>,
    pub report: Option<String>,
}

/// Every node kind, spelled exactly as the TypeScript compiler and the
/// conformance runner spell it.
pub const NODE_KINDS: [&str; 22] = [
    "Project",
    "Compare",
    "Detect",
    "Align",
    "UnitExpr",
    "ResponseExpr",
    "NearestUnit",
    "CorrExpr",
    "Var",
    "Num",
    "Let",
    "Bind",
    "Relax",
    "Sweep",
    "For",
    "Claim",
    "Record",
    "Drop",
    "Open",
    "MethodDecl",
    "FrameBlock",
    "Program",
];
