#!/usr/bin/env python3
"""Dump the reference parser's AST for every corpus program, as JSON.

This is the oracle for Stage A. A compiler's parser is correct when its
AST is byte-identical to this file's -- not when it "looks right". The
positives especially: an AST that differs in a field the checker later
reads is a divergence that would only surface as a wrong verdict.

Programs that fail to PARSE are recorded with their error class instead
of a tree, so the parse-error negatives are covered too.

Run:  python synopsis/corpus/dump_ref_ast.py
Out:  synopsis/corpus/ref_ast.json
"""

from __future__ import annotations

import importlib.util
import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
VALIDATION = (REPO / "vivid-symbolism" / "publications"
              / "column-synopsis-genomic-script" / "validation")


def load(name: str):
    spec = importlib.util.spec_from_file_location(name, VALIDATION / f"{name}.py")
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load {name}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def to_json(x, lang):
    """Serialise a reference AST node to the shape both compilers emit."""
    # dataclass node -> {"node": ClassName, ...fields}
    if isinstance(x, lang.Node):
        out = {"node": type(x).__name__}
        # __dataclass_fields__ preserves declaration order, and `line`
        # is declared on the base so it comes first -- same as the
        # generated TS/Rust.
        for fname in x.__dataclass_fields__:
            out[fname] = to_json(getattr(x, fname), lang)
        return out
    if isinstance(x, dict):
        # Params: a list of [k, v] pairs, because order is significant
        # and a JSON object does not promise it.
        return [[k, to_json(v, lang)] for k, v in x.items()]
    if isinstance(x, (list, tuple)):
        # The empty tuple is Align.resp when there is no response
        # clause; both compilers spell that `null`.
        if isinstance(x, tuple) and len(x) == 0:
            return None
        return [to_json(v, lang) for v in x]
    if isinstance(x, bool):
        return x
    if isinstance(x, float):
        if math.isnan(x) or math.isinf(x):
            raise SystemExit(f"non-finite literal in AST: {x}")
        # Integral floats round-trip as ints so JS's Number and
        # Python's float agree on the JSON text.
        return int(x) if x.is_integer() else x
    return x


def main() -> int:
    sys.path.insert(0, str(VALIDATION))
    for n in ("core", "semantics", "lang"):
        load(n)
    lang = sys.modules["lang"]
    experiments = load("experiments")

    def class_name(cls) -> str:
        return "TypeError" if cls.__name__ == "TypeError_" else cls.__name__

    entries = []
    for name, src in experiments.POSITIVE:
        entries.append({"name": name, "group": "positive",
                        "ast": to_json(lang.parse(src), lang)})

    for name, src, _cls in experiments.NEGATIVE:
        try:
            tree = lang.parse(src)
        except lang.SynopsisError as e:
            entries.append({"name": name, "group": "negative",
                            "parse_error": class_name(type(e)),
                            "message": str(e.args[0] if e.args else "")})
        else:
            # Parses fine; it is the CHECKER that must refuse it. The
            # tree is still recorded, because a parser that builds the
            # wrong tree here would make the checker refuse for the
            # right class by accident.
            entries.append({"name": name, "group": "negative",
                            "ast": to_json(tree, lang)})

    # Programs that must NOT parse at all -- the forms whose absence is
    # what makes thm:total and thm:noexact properties of the language.
    # E27 checks these explicitly.
    forbidden = {
        "while": 'open a = "x"\nunder f { while x { } }\nreport to "r"',
        "fix": 'open a = "x"\nunder f { fix x = y }\nreport to "r"',
        "recurse": 'open a = "x"\nunder f { recurse f }\nreport to "r"',
        "index": 'open a = "x"\nunder f { let y = a[3] }\nreport to "r"',
    }
    forbid = []
    for label, src in forbidden.items():
        try:
            lang.parse(src)
        except lang.SynopsisError as e:
            forbid.append({"name": label, "src": src,
                           "parse_error": class_name(type(e))})
        else:
            raise SystemExit(
                f"reference PARSED a forbidden form ({label}); the grammar "
                f"no longer excludes it and thm:total is in question")

    doc = {
        "$comment": (
            "GENERATED by synopsis/corpus/dump_ref_ast.py. The reference "
            "parser's output for every corpus program. A compiler's parser "
            "conforms when it reproduces these trees exactly."),
        "entries": entries,
        "must_not_parse": forbid,
    }
    out = HERE / "ref_ast.json"
    out.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")

    n_tree = sum(1 for e in entries if "ast" in e)
    n_perr = sum(1 for e in entries if "parse_error" in e)
    print(f"wrote {out.relative_to(REPO)}")
    print(f"  trees       : {n_tree}")
    print(f"  parse errors: {n_perr}")
    print(f"  must-not-parse forms: {len(forbid)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
