#!/usr/bin/env python3
"""Extract the conformance corpus from the reference implementation.

The corpus is NOT hand-maintained. It is read out of
validation/experiments.py -- the same POSITIVE and NEGATIVE lists that
the manuscript's E26 and E28 run against -- so that the TypeScript and
Rust compilers are tested against exactly what the reference semantics
was validated on. Hand-copying would let the three drift apart silently,
which is the one failure this whole arrangement exists to prevent.

Run:  python synopsis/corpus/extract.py
Out:  synopsis/corpus/corpus.json
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
VALIDATION = (REPO / "vivid-symbolism" / "publications"
              / "column-synopsis-genomic-script" / "validation")


def load(name: str):
    """Import a reference module by path, without installing anything."""
    spec = importlib.util.spec_from_file_location(name, VALIDATION / f"{name}.py")
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load {name} from {VALIDATION}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def main() -> int:
    if not VALIDATION.is_dir():
        raise SystemExit(f"reference validation dir not found: {VALIDATION}")

    sys.path.insert(0, str(VALIDATION))
    core = load("core")          # noqa: F841  -- experiments imports it
    semantics = load("semantics")  # noqa: F841
    lang = load("lang")
    experiments = load("experiments")

    # ---- error class names, as the compilers must report them --------
    # We emit the CLASS NAME, not the Python type, so TS and Rust can
    # compare against a string. `TypeError_` is spelled with a trailing
    # underscore in the reference only to avoid shadowing the builtin;
    # the language's name for it is `TypeError`.
    def class_name(cls) -> str:
        return "TypeError" if cls.__name__ == "TypeError_" else cls.__name__

    positive = [{"name": n, "src": s} for n, s in experiments.POSITIVE]
    negative = [{"name": n, "src": s, "expect": class_name(c)}
                for n, s, c in experiments.NEGATIVE]

    # ---- self-check against the reference ----------------------------
    # If the reference does not itself accept the positives and reject
    # the negatives with these classes, the corpus is wrong and nothing
    # downstream is meaningful. Fail loudly here rather than shipping it.
    problems: list[str] = []

    for item in positive:
        ok, err = lang.accepts(item["src"])
        if not ok:
            problems.append(f"POSITIVE {item['name']} rejected by reference: {err}")

    for item in negative:
        try:
            lang.check(item["src"])
        except lang.SynopsisError as e:
            got = class_name(type(e))
            want = item["expect"]
            # Subclass relationships are real: ArityError IS-A TypeError.
            # The corpus records the most specific class the reference
            # raises; a compiler matching a superclass is checked in the
            # runner, not here.
            if got != want:
                # Accept a strict subclass of the declared expectation.
                declared = getattr(lang, want, None) or getattr(
                    lang, want + "_", None)
                if not (declared and isinstance(e, declared)):
                    problems.append(
                        f"NEGATIVE {item['name']}: reference raised {got}, "
                        f"corpus declares {want}")
        except Exception as e:  # noqa: BLE001
            problems.append(
                f"NEGATIVE {item['name']}: non-Synopsis error {type(e).__name__}: {e}")
        else:
            problems.append(f"NEGATIVE {item['name']} was ACCEPTED by reference")

    if problems:
        print("corpus self-check FAILED:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    # ---- the error hierarchy, so runners can check subclassing -------
    hierarchy = {}
    for nm in ("ParseError", "TypeError_", "ArityError", "ScopeError",
               "ResidueError", "ParameterError", "TerminationError"):
        cls = getattr(lang, nm)
        parents = [class_name(b) for b in cls.__mro__[1:]
                   if issubclass(b, lang.SynopsisError) and b is not cls]
        hierarchy[class_name(cls)] = parents

    # ---- required parameters, as data --------------------------------
    required_params = {k: sorted(v) for k, v in lang.REQUIRED_PARAMS.items()}

    doc = {
        "$comment": (
            "GENERATED by synopsis/corpus/extract.py from "
            "validation/experiments.py. Do not edit by hand; re-run the "
            "extractor. Every entry has been checked against the "
            "reference implementation at extraction time."),
        "keywords": sorted(lang.KEYWORDS),
        "result_types": sorted(lang.RESULT_TYPES),
        "required_params": required_params,
        "error_hierarchy": hierarchy,
        "positive": positive,
        "negative": negative,
    }

    out = HERE / "corpus.json"
    out.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")

    by_class: dict[str, int] = {}
    for item in negative:
        by_class[item["expect"]] = by_class.get(item["expect"], 0) + 1

    print(f"wrote {out.relative_to(REPO)}")
    print(f"  positive : {len(positive)}")
    print(f"  negative : {len(negative)}")
    for k in sorted(by_class):
        print(f"      {k:18s} {by_class[k]}")
    print(f"  keywords : {len(doc['keywords'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
