#!/usr/bin/env python3
"""Generate the TypeScript and Rust AST definitions from corpus/ast.json.

The node set is declared once. Both compilers read the same declaration,
so they cannot disagree about whether a field is optional -- which is the
specific way two implementations of one language start diverging.

Run:  python synopsis/corpus/gen_ast.py
Out:  synopsis/ts/src/ast.ts
      synopsis/rs/src/ast.rs
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]

BANNER_TS = """// GENERATED by synopsis/corpus/gen_ast.py from synopsis/corpus/ast.json.
// Do not edit by hand -- edit the JSON and re-run the generator.
"""

BANNER_RS = """// GENERATED by synopsis/corpus/gen_ast.py from synopsis/corpus/ast.json.
// Do not edit by hand -- edit the JSON and re-run the generator.
"""

# Groups, in emission order, and which union each belongs to.
GROUPS = [
    ("expressions", "Expr"),
    ("statements", "Stmt"),
    ("declarations", "Decl"),
    ("toplevel", None),      # FrameBlock and Program stand alone
]

# Fields whose declared type is a group union but whose group is not the
# one being emitted. Handled by the type table; listed here only for the
# reader's benefit.


def load() -> dict:
    return json.loads((HERE / "ast.json").read_text(encoding="utf-8"))


def nodes_of(doc: dict, group: str) -> dict:
    """The node entries of a group, minus the JSON comment keys."""
    return {k: v for k, v in doc[group].items() if not k.startswith("$")}


# --------------------------------------------------------------------------
# TypeScript
# --------------------------------------------------------------------------

def ts_type(doc: dict, t: str) -> str:
    if t == "bool":
        return "boolean"
    entry = doc["types"].get(t)
    if entry is None:
        raise SystemExit(f"ast.json: unknown field type {t!r}")
    return entry["ts"]


def emit_ts(doc: dict) -> str:
    out: list[str] = [BANNER_TS]
    out.append("/** A parameter block: ordered, because the report prints "
               "parameters in source order. */")
    out.append("export type Params = Map<string, number | string>;\n")

    for group, union in GROUPS:
        nodes = nodes_of(doc, group)
        for name, spec in nodes.items():
            out.append(f"/** {spec['doc']} */")
            out.append(f"export interface {name} {{")
            # The discriminant is `node`, not `kind`: `Detect` has a
            # real field called `kind` (peaks | top) and the two must
            # not collide. Renaming the DISCRIMINANT keeps every
            # semantic field named exactly as the reference names it.
            out.append(f'  readonly node: "{name}";')
            out.append("  readonly line: number;")
            for fname, ftype in spec["fields"].items():
                out.append(f"  readonly {fname}: {ts_type(doc, ftype)};")
            out.append("}\n")
        if union:
            members = " | ".join(nodes)
            out.append(f"export type {union} = {members};\n")

    # Discriminant helpers: a closed union is only useful if exhaustiveness
    # is checkable, and both compilers must agree on the tag set.
    all_names = [n for g, _ in GROUPS for n in nodes_of(doc, g)]
    out.append("/** Every node tag. The discriminant field is `node`. */")
    out.append("export type NodeKind =")
    for i, n in enumerate(all_names):
        tail = ";" if i == len(all_names) - 1 else ""
        out.append(f'  | "{n}"{tail}')
    out.append("")
    out.append(f"export const NODE_KINDS: readonly NodeKind[] = [")
    for n in all_names:
        out.append(f'  "{n}",')
    out.append("] as const;")
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# Rust
# --------------------------------------------------------------------------

def rs_type(doc: dict, t: str) -> str:
    if t == "bool":
        return "bool"
    entry = doc["types"].get(t)
    if entry is None:
        raise SystemExit(f"ast.json: unknown field type {t!r}")
    return entry["rs"]


def emit_rs(doc: dict) -> str:
    out: list[str] = [BANNER_RS]
    out.append("use crate::params::Params;\n")

    for group, union in GROUPS:
        nodes = nodes_of(doc, group)
        if union:
            out.append(f"#[derive(Debug, Clone, PartialEq)]")
            out.append(f"pub enum {union} {{")
            for name, spec in nodes.items():
                # Doc comments inside an enum body attach to the variant.
                out.append(f"    /// {spec['doc']}")
                out.append(f"    {name} {{")
                out.append("        line: usize,")
                for fname, ftype in spec["fields"].items():
                    out.append(f"        {fname}: {rs_type(doc, ftype)},")
                out.append("    },")
            out.append("}\n")
        else:
            for name, spec in nodes.items():
                out.append(f"/// {spec['doc']}")
                out.append("#[derive(Debug, Clone, PartialEq)]")
                out.append(f"pub struct {name} {{")
                out.append("    pub line: usize,")
                for fname, ftype in spec["fields"].items():
                    out.append(f"    pub {fname}: {rs_type(doc, ftype)},")
                out.append("}\n")

    # The tag set, so the Rust side can name kinds the same way the TS side
    # and the conformance runner do.
    all_names = [n for g, _ in GROUPS for n in nodes_of(doc, g)]
    out.append("/// Every node kind, spelled exactly as the TypeScript "
               "compiler and the")
    out.append("/// conformance runner spell it.")
    out.append(f"pub const NODE_KINDS: [&str; {len(all_names)}] = [")
    for n in all_names:
        out.append(f'    "{n}",')
    out.append("];")
    out.append("")
    return "\n".join(out)


def main() -> int:
    doc = load()

    ts_path = REPO / "synopsis" / "ts" / "src" / "ast.ts"
    rs_path = REPO / "synopsis" / "rs" / "src" / "ast.rs"
    ts_path.parent.mkdir(parents=True, exist_ok=True)
    rs_path.parent.mkdir(parents=True, exist_ok=True)

    ts_path.write_text(emit_ts(doc), encoding="utf-8")
    rs_path.write_text(emit_rs(doc), encoding="utf-8")

    n = sum(len(nodes_of(doc, g)) for g, _ in GROUPS)
    print(f"wrote {ts_path.relative_to(REPO)}")
    print(f"wrote {rs_path.relative_to(REPO)}")
    print(f"  node kinds : {n}")
    for g, union in GROUPS:
        print(f"      {g:14s} {len(nodes_of(doc, g)):2d}"
              f"{'  -> ' + union if union else ''}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
