title: Gospel
description: Advanced Genomic Analysis Framework with AI Integration
url: "https://your-username.github.io"
baseurl: "/gospel"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Theme customization
minima:
  skin: dark
  social_links:
    github: fullscreen-triangle/gospel

# Navigation
header_pages:
  - index.md
  - getting-started.md
  - architecture.md
  - domains.md
  - cli-reference.md
  - api-reference.md
  - examples.md
  - contributing.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Math support
kramdown:
  math_engine: mathjax 