// GENERATED by synopsis/corpus/gen_ast.py from synopsis/corpus/ast.json.
// Do not edit by hand -- edit the JSON and re-run the generator.

/** A parameter block: ordered, because the report prints parameters in source order. */
export type Params = Map<string, number | string>;

/** project <src> by <projector>(<args>)  -- Sec 7.3 */
export interface Project {
  readonly node: "Project";
  readonly line: number;
  readonly src: Expr;
  readonly projector: string;
  readonly args: Params;
}

/** compare <l> against <r> by <method>(<params>) */
export interface Compare {
  readonly node: "Compare";
  readonly line: number;
  readonly left: Expr;
  readonly right: Expr;
  readonly method: string;
  readonly params: Params;
}

/** detect peaks|top in <src> { params }  -- `kind` selects the result type */
export interface Detect {
  readonly node: "Detect";
  readonly line: number;
  readonly kind: string;
  readonly src: Expr;
  readonly params: Params;
}

/** align central(a,b) response(c,d) under phi_c, phi_r { theta }  -- Thm 9.5. has_response_clause=false is the false-friend mistake the arity rule must refuse. */
export interface Align {
  readonly node: "Align";
  readonly line: number;
  readonly central: [Expr, Expr];
  readonly resp: [Expr, Expr] | null;
  readonly corrs: string[];
  readonly params: Params;
  readonly has_response_clause: boolean;
}

/** unit <src> anchors <n>  -- Def 5.4 anchors/residue split */
export interface UnitExpr {
  readonly node: "UnitExpr";
  readonly line: number;
  readonly src: Expr;
  readonly anchors: number;
}

/** response <src> by <method>  -- method=null means ANONYMOUS, which Rule 6.7 refuses */
export interface ResponseExpr {
  readonly node: "ResponseExpr";
  readonly line: number;
  readonly src: Expr;
  readonly method: string | null;
}

/** nearest_unit <net> to <unit> */
export interface NearestUnit {
  readonly node: "NearestUnit";
  readonly line: number;
  readonly net: Expr;
  readonly to: Expr;
}

/** corr from <src> to <dst> by <by> */
export interface CorrExpr {
  readonly node: "CorrExpr";
  readonly line: number;
  readonly src: Expr;
  readonly dst: Expr;
  readonly by: string;
}

/** a bound name */
export interface Var {
  readonly node: "Var";
  readonly line: number;
  readonly name: string;
}

/** a numeric literal */
export interface Num {
  readonly node: "Num";
  readonly line: number;
  readonly value: number;
}

export type Expr = Project | Compare | Detect | Align | UnitExpr | ResponseExpr | NearestUnit | CorrExpr | Var | Num;

/** let x = <expr>. NOTE: the reference parser has an `ann` branch for `let x : ty = e`, but ':' is not in the tokenizer's punctuation class, so that branch is unreachable -- `let x : seq` fails with `unexpected character ':'`. The field is kept (always null) so the two implementations stay structurally identical to the reference; neither compiler may start accepting the annotation without a decision, because that would extend the language. */
export interface Let {
  readonly node: "Let";
  readonly line: number;
  readonly name: string;
  readonly ann: string | null;
  readonly expr: Expr;
}

/** bind v, res = <expr>  -- introduces BOTH the value and its residue; Cor 9.8 requires the residue be consumed before the frame closes */
export interface Bind {
  readonly node: "Bind";
  readonly line: number;
  readonly value: string;
  readonly residue: string;
  readonly expr: Expr;
}

/** relax <target> until quiescent { eta ; theta }  -- Thm 9.3 refuses eta <= 0 */
export interface Relax {
  readonly node: "Relax";
  readonly line: number;
  readonly target: string;
  readonly params: Params;
}

/** sweep x in lo..hi step s { }  or  sweep x in [..] { }  -- Thm 9.1: trip count fixed on entry. `values` non-null means the literal-list form, and lo/hi/step are then unused. */
export interface Sweep {
  readonly node: "Sweep";
  readonly line: number;
  readonly var: string;
  readonly lo: number;
  readonly hi: number;
  readonly step: number;
  readonly values: number[] | null;
  readonly body: Stmt[];
}

/** for u in items(<src>) [where <guard>] { }  -- finite item set, so total */
export interface For {
  readonly node: "For";
  readonly line: number;
  readonly var: string;
  readonly src: Expr;
  readonly guard: string | null;
  readonly body: Stmt[];
}

/** claim "text" = <expr> */
export interface Claim {
  readonly node: "Claim";
  readonly line: number;
  readonly text: string;
  readonly expr: Expr;
}

/** record a, b, c  -- consumes pending residue */
export interface Record {
  readonly node: "Record";
  readonly line: number;
  readonly names: string[];
}

/** drop x  -- explicitly abandons a residue; the report records that it was abandoned rather than omitting it */
export interface Drop {
  readonly node: "Drop";
  readonly line: number;
  readonly name: string;
}

export type Stmt = Let | Bind | Relax | Sweep | For | Claim | Record | Drop;

/** open name = "path" */
export interface Open {
  readonly node: "Open";
  readonly line: number;
  readonly name: string;
  readonly path: string;
}

/** method name = spec(params)  -- Rule 6.7: responses must name a declared method */
export interface MethodDecl {
  readonly node: "MethodDecl";
  readonly line: number;
  readonly name: string;
  readonly spec: string;
  readonly params: Params;
}

export type Decl = Open | MethodDecl;

/** under <name> { }  -- Sec 7.4. Each block introduces a fresh frame index phi; types carrying different phi are DIFFERENT TYPES, which is what gives Thm 9.6. */
export interface FrameBlock {
  readonly node: "FrameBlock";
  readonly line: number;
  readonly name: string;
  readonly body: Stmt[];
}

/** the whole program. `report` is the terminal `report to "path"`; null is a ParseError, since there is no silent program (Rule 6.11). */
export interface Program {
  readonly node: "Program";
  readonly line: number;
  readonly decls: Decl[];
  readonly frames: FrameBlock[];
  readonly report: string | null;
}

/** Every node tag. The discriminant field is `node`. */
export type NodeKind =
  | "Project"
  | "Compare"
  | "Detect"
  | "Align"
  | "UnitExpr"
  | "ResponseExpr"
  | "NearestUnit"
  | "CorrExpr"
  | "Var"
  | "Num"
  | "Let"
  | "Bind"
  | "Relax"
  | "Sweep"
  | "For"
  | "Claim"
  | "Record"
  | "Drop"
  | "Open"
  | "MethodDecl"
  | "FrameBlock"
  | "Program";

export const NODE_KINDS: readonly NodeKind[] = [
  "Project",
  "Compare",
  "Detect",
  "Align",
  "UnitExpr",
  "ResponseExpr",
  "NearestUnit",
  "CorrExpr",
  "Var",
  "Num",
  "Let",
  "Bind",
  "Relax",
  "Sweep",
  "For",
  "Claim",
  "Record",
  "Drop",
  "Open",
  "MethodDecl",
  "FrameBlock",
  "Program",
] as const;
